# Generated by Django 2.0.5 on 2020-12-14 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admins',
            new_name='admins_db',
        ),
    ]
