# Generated by Django 2.0.5 on 2020-12-21 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_users_db'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users_db',
            new_name='dummy_db',
        ),
    ]
