# Generated by Django 2.0.5 on 2020-12-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20201221_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='products_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('image', models.FileField(max_length=50, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='dummy_db',
            name='userid',
        ),
        migrations.DeleteModel(
            name='dummy_db',
        ),
    ]
