# Generated by Django 2.0.5 on 2020-12-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20201221_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='recipies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ingredients', models.CharField(max_length=50)),
                ('instructions', models.CharField(max_length=50)),
                ('image', models.FileField(max_length=50, upload_to='')),
            ],
        ),
    ]
