# Generated by Django 2.0.5 on 2020-12-22 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_recipies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipies',
            old_name='name',
            new_name='name1',
        ),
    ]
