# Generated by Django 2.0.5 on 2020-12-23 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20201222_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipies',
            old_name='name1',
            new_name='recipiename',
        ),
    ]
