# Generated by Django 2.0.5 on 2020-12-23 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20201223_1018'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='recipies',
            new_name='recipie_db',
        ),
    ]
