# Generated by Django 2.0.5 on 2020-12-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20201223_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipie_db',
            name='ingredients',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recipie_db',
            name='instructions',
            field=models.TextField(max_length=50),
        ),
    ]
