# Generated by Django 2.0.5 on 2020-12-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20201224_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins_db',
            name='image',
            field=models.ImageField(upload_to='adminimage'),
        ),
        migrations.AlterField(
            model_name='products_db',
            name='image',
            field=models.ImageField(upload_to='productimage'),
        ),
        migrations.AlterField(
            model_name='recipie_db',
            name='image',
            field=models.ImageField(upload_to='recipieimage'),
        ),
    ]
