# Generated by Django 3.1.4 on 2020-12-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20201224_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins_db',
            name='image',
            field=models.ImageField(upload_to='adminimage/'),
        ),
    ]
